"""Add additional field in Job table

Revision ID: 3dbb7259a78d
Revises: 5895745d1dce
Create Date: 2025-05-20 12:25:56.220844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dbb7259a78d'
down_revision: Union[str, None] = '5895745d1dce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('logo', sa.String(), nullable=True))
    op.drop_column('job', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('job', 'logo')
    # ### end Alembic commands ###
