"""Update Job table

Revision ID: 55845a524f3b
Revises: 8dc03cdbe8fc
Create Date: 2025-05-20 13:56:32.417656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55845a524f3b'
down_revision: Union[str, None] = '8dc03cdbe8fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('company', sa.String(), nullable=True))
    op.alter_column('job', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('job', 'location',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job', 'location',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('job', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('job', 'company')
    # ### end Alembic commands ###
