"""Update Job Table

Revision ID: 8e8361a54717
Revises: 5453d29ac122
Create Date: 2025-03-26 13:05:30.760266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e8361a54717'
down_revision: Union[str, None] = '5453d29ac122'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('job_employer_id_fkey', 'job', type_='foreignkey')
    op.create_foreign_key(None, 'job', 'user', ['user_id'], ['id'])
    op.drop_column('job', 'employer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('employer_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'job', type_='foreignkey')
    op.create_foreign_key('job_employer_id_fkey', 'job', 'user', ['employer_id'], ['id'])
    op.drop_column('job', 'user_id')
    # ### end Alembic commands ###
