"""Update Application Table

Revision ID: ecb8aa184ee6
Revises: 4beacd114cae
Create Date: 2025-03-29 10:28:57.985225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecb8aa184ee6'
down_revision: Union[str, None] = '4beacd114cae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('application', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application', 'updated_at')
    op.drop_column('application', 'created_at')
    # ### end Alembic commands ###
